---
# tasks file for ansible-rhelphp5
- name: add latest epel release
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: add webtatic release
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present

- name: install PHP 5.5 mod_php SAPI
  package: name={{ item }} state=present update_cache=yes
  with_items:
      - php55w
      - php55w-opcache
  
- name: install PHP 5.5 odbc
  package: name=php55w-odbc state=present update_cache=yes

- name: install httpd
  package: name=httpd state=present update_cache=yes

- name : copy over index.php
  template: src=templates/index.php dest=/var/www/html/index.php
  notify: restart httpd

- name: Install goss
  shell: 'curl -fsSL https://goss.rocks/install | sh'
  args:
    creates: "/usr/local/bin/goss"

- name: Place goss file
  template: src=templates/goss.json dest=/goss.json

- name: validate goss
  command: 'goss --gossfile "/goss.json" validate --format documentation'

